### PR TITLE
Multiple small improvements

### LINKED ISSUE #13: Implement the copy button
The copy button should copy the hex code into user clipboard with the # sign

### LINKED ISSUE #21: Responsiveness up to 240 px at least
Given that the smalest commonly used mobile devices are 320px wide and that the persona bar is 80px wide, this leaves a 240px usable in the panel, so we need to make at least the components to be somehow usable at 240px wide. Ideally 220px to allow a little padding too. This will not solve the persona bar responsiveness but we should at least make the new components as such if we hope to have a responsive persona bar one day...

@david-poindexter this will be very easy with flexbox and I already have tested something here but not coded it yet, we we talk, just wanted to have this logged as an issue here.

### PR DESCRIPTION
**Pull request by valadas**
I was playing with the project during a boring meeting and came up with some improvements, this is a bit of a mixed bag and I am sorry to mix concerns in a single PR.

@david-poindexter I know you are in vacation but when you are back or if you feel like taking a look at this, feel free to comment. Also if you have other ideas on how to accomplish some of these things...

In This PR:
* Adds a custom number input field to solve the problem centering the values with the labels responsively.
* Adds a configurable shift multiplier to set by how much to change values when using the keyboard arrows and holding shift
* Implements the copy button ( closes #13 )
* Uses javascript to make the controls responsive in relation to the component size and not the screen size ( closes #21 ) Let me know what you think of how this wraps on small widths...
* Adds some documentation
* Replaces the 3 switch mode buttons by a single one
* Reduces the size a bit for the circle of the preview color (personal preference here for when the component in a rather small container, open to opinions on this ???
* Adds a transition to the switching of input fields

### CODE REVIEW

**Review by david-poindexter — COMMENTED** [review]
@valadas - I just reviewed all this the best I could from my phone and I see no glaring issues.  It will most likely be Friday or Monday before I am able to thoroughly review this, but it looks good.  Thanks so much for the hard work!

**Comment by valadas** [comment]
I am merging this because I need this for the next set of changes, we can always edit if required

**Comment by david-poindexter** [comment]
@valadas I started reviewing this yesterday but just didn’t have enough time since it was my first day back in the office.  I will try to get to this as soon as possible though.

**Comment by david-poindexter** [comment]
@valadas I finally got some time today to review all this and I think it is all great.  Thanks for the work on this!  I am going to create a few minor issues and submit PRs for them as soon as possible.

**Pull request merged**
